---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercise2
spec:
  selector:
    matchLabels:
      app: exercise2
  template:
    metadata:
      labels:
        app: exercise2
    spec:
      containers:
      - name: exercise2
        image: postgres:10.15
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: POSTGRES_PASSWORD
            value: example
